### PR TITLE
created Contribute.md

### PR DESCRIPTION
**Pull request by jangidkrishna**
Hope u like it

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
Hi! Thanks for PR.
Make sure you have checked points in PR Template correctly.

**Comment by jangidkrishna** [comment]
yeah i have mentioned it give it a look

**Review by aashutoshrathi — CHANGES_REQUESTED** [review]
Make all the subheading active, by adding `###` in front of them and check for grammatical errors once again.

**Comment by jangidkrishna** [comment]
have a look at it now

**Comment by jangidkrishna** [comment]
can u add hacktoberfest label to it please

**Comment by aashutoshrathi** [comment]
Give space after `###`

**Comment by jangidkrishna** [comment]
did u try it

**Comment by aashutoshrathi** [comment]
Thanks @jangidkrishna

**Review by aashutoshrathi — APPROVED** [review]

**Pull request merged**
