### PR TITLE
Added Demo for RPSLS

### LINKED ISSUE #1: Demo for RPSLS needed

### PR DESCRIPTION
**Pull request by darshkpatel**
fixed [#1](https://github.com/aashutoshrathi/Python-Scripts-and-Games/issues/1)
Added Demo GIF

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
Hi!, Thanks for PR, make sure you have checked all correct points in PR Template.

**Comment by aashutoshrathi** [comment]
Nice, @darshkpatel Can we add more features in GIF?

**Comment by darshkpatel** [comment]
added a commit

**Comment by aashutoshrathi** [comment]
Thanks a lot @darshkpatel 
Feel free to watch and star this repo.

**Review by aashutoshrathi — APPROVED** [review]

**Pull request merged**
