### PR TITLE
Fixed 6

### PR DESCRIPTION
**Pull request by darshkpatel**
The Program gave the following error in Python 2.7:
```File "RPSL.py", line 82, in rpsls
  name = input()
  File "<string>", line 1, in <module>
NameError: name 'rock' is not definedname = input()
  File "<string>", line 1, in <module>
NameError: name 'rock' is not defined
````

Fixed by using legacy input method which is compatible in both python 2.7 and 3

Fixed stray ' ( )  ' after selecting choice

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
Hi!, Thanks for PR, make sure you have checked all correct points in PR Template.

**Comment by aashutoshrathi** [comment]
Thanks, @darshkpatel Please create an issue and Link this PR with it, so that I can merge it.

**Comment by darshkpatel** [comment]
Fixes #6

**Comment by aashutoshrathi** [comment]
Do your solution work in Python 2?

**Comment by darshkpatel** [comment]
The two major python distributions are 2.7 and 3
It works on both of em

**Pull request closed without merging**
